Update deploy pipeline
pagopa/io-functions-cgn-operator-search pull request #9
Opened 2021-05-17 08:39 UTC by ElfoLiNk

#### List of Changes

#### Motivation and Context

#### How Has This Been Tested?

#### Screenshots (if appropriate):

#### Types of changes

- [x] Chore (nothing changes by a user perspective)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2021-05-17 12:17 UTC, pasqualedevita requested changes
check suggestions, maybe there was some errors

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +    FUNCTION_APP_RESOURCE_GROUP_NAME: $(PROD_WEB_APP_RESOURCE_GROUP_NAME)
```suggestion
    WEB_APP_NAME: $(PROD_WEB_APP_NAME)
    WEB_APP_RESOURCE_GROUP_NAME: $(PROD_WEB_APP_RESOURCE_GROUP_NAME)
```

Configs do not match with pipeline definition

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +    FUNCTION_APP_RESOURCE_GROUP_NAME: $(UAT_WEB_APP_RESOURCE_GROUP_NAME)
```suggestion
    WEB_APP_NAME: $(UAT_WEB_APP_NAME)
    WEB_APP_RESOURCE_GROUP_NAME: $(UAT_WEB_APP_RESOURCE_GROUP_NAME)
```

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +  vmImage: 'ubuntu-latest'
```suggestion
  vmImage: 'windows-2019'
```
We use windows function-app please use windows image machine

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
>                semver: '${{ parameters.RELEASE_SEMVER }}'
```suggestion
              release_branch: '$(DEFAULT_BRANCH)'
              semver: '${{ parameters. DEFAULT_BRANCH }}'
```
not needed but better to specify

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +              resourceGroupName: '$(FUNCTION_APP_RESOURCE_GROUP_NAME)'
```suggestion
              resourceGroupName: '$(WEB_APP_RESOURCE_GROUP_NAME)'
```

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +              appName: '$(FUNCTION_APP_NAME)'
```suggestion
              appName: '$(WEB_APP_NAME)'
```

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +              appName: '$(FUNCTION_APP_NAME)'
```suggestion
              appName: '$(WEB_APP_NAME)'
              resourceGroupName: '$(WEB_APP_RESOURCE_GROUP_NAME)'
```

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +              resourceGroupName: '$(FUNCTION_APP_RESOURCE_GROUP_NAME)'
```suggestion
              resourceGroupName: '$(WEB_APP_RESOURCE_GROUP_NAME)'
```

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +              webAppName: '$(FUNCTION_APP_NAME)'
```suggestion
              appName: '$(WEB_APP_NAME)'
```

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +              resourceGroupName: '$(FUNCTION_APP_RESOURCE_GROUP_NAME)'
```suggestion
              resourceGroupName: '$(WEB_APP_RESOURCE_GROUP_NAME)'
```

2021-05-17 12:17 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +              appName: '$(FUNCTION_APP_NAME)'
```suggestion
              appName: '$(WEB_APP_NAME)'
```

2021-05-17 12:55 UTC, pasqualedevita commented on .devops/deploy-pipelines.yml
> +          - task: AzureWebApp@1
```suggestion
          - task: AzureFunctionApp@1
```

2021-05-17 13:09 UTC, pasqualedevita requested changes
check suggestion

2021-05-17 14:27 UTC, pasqualedevita submitted a review, later dismissed

2021-05-17 14:55 UTC, ElfoLiNk commented
@AleDore UAT deployment done. Could you approve?

2021-05-17 15:12 UTC, pasqualedevita submitted a review, later dismissed

2021-05-18 13:59 UTC, AleDore approved these changes

2021-05-18 14:11 UTC, merged